# Cria recurso externo do cluster, pode ser utilizado um nginx com proxypass para um unico IP

apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-mamede-java
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
       # 30000 ~ 32767
  selector:
    app: mamede-java

# kubectl apply -f node-port-nginx.yml
# kubectl describe -f node-port-nginx.yml
# kubectl delete -f node-port-nginx.yml